import React from 'react'
import '../../style/pages/omnie.css'

const OMniePage = () => {
  return (
    <div className='omnieContainer'>
      <h2>Coś o sobie:</h2>
      <p>Cześć, nazywam się Paweł i mieszkam w małym mieście Borkowie na Pomorzu. W tym roku (2022) skończyłem 36 lat. Część z Was zapewne kojarzy mnie z mojego kanału na YouTube lub streamów na Twitch. Jestem na ogół bardzo spokojnym człowiekiem, wręcz nieśmiałym na początku. Muszę się przyzwyczaić do nowych ludzi, żeby móc normalnie funkcjonować. Jak jestem wśród „swoich” bawię się najlepiej i czasem nawet rozkręcam imprezę. Czasami bywam egoistą, ale to z powodu mieszkania samemu przez kilka lat. Jestem też leniem, co można czasami zaobserwować przy częstotliwości ukazujących się filmów. Patrzę na świat i całe jego otoczenie okiem realisty, przez co wszelakie bóstwa są mi obojętne i nie utożsamiam się z żadnym z nich. Wszelkie spory staram się rozwiązywać i nie cierpię niedopowiedzeń i obrażania się.</p>
      <h2>Growe doświadczenia:</h2>
      <p>Żeby zrozumieć dlaczego zajmuję się grami z „szaraczka” trzeba by cofnąć się do późnych lat 90'tych, kiedy to rodzice w końcu kupili mi konsole PlayStation 1. Ilość gier ogranych w tamtych latach była spora, ale nie udało mi się uruchomić, albo skończyć większości. Po pewnym czasie otrzymałem komputer, z którym żyłem w związku do czasów studiów. Na tych studiach kolega przypomniał mi o PlayStation i namówił do zakupu dwójki (zaznaczam że na rynku w tym czasie była już PS3). Dzięki niemu zagrałem w świetne God of War I i II, Gran Turismo 4, Champions of Norrath i Dragon Ball Z Infinite World. W te gry zagrywałem się godzinami i zacząłem sobie przypominać starsze tytuły z „szaraczka”, co zrodziło poszukiwanie kontynuacji. Epizod z PlayStation 3 zacząłem jakieś 10 lat temu, kiedy to znajomy z pracy sprzedał mi ją za dość niską cenę. To był moment kiedy w 100% przeniosłem się na konsolę. Od tamtej pory nazbierało się około 2000 gier na różne platformy.</p>
      <h2>Początki „Historii Gier PlayStation”</h2>
      <p>Skąd wziął się pomysł na kanał? Wystarczyło zamiłowanie do gier i kinematografii, zbyt dużo wolnego czasu i chęć stworzenia czegoś nietypowego (na polskim YT). Uświadomiłem sobie, że mam gry, ochotę na nagranie i bardzo skromny arsenał sprzętowy do nagrywania. We wrześniu 2013 zrodził się pomysł na utworzenie kanału na YT poświęcony grom. Tylk,o że jakie gry? Nowe? Sprawdziłem recenzje i okazało się że jest tego multum i „wybicie się” będzie piekielnie trudne. No to może gry z PS2? Nie ma tego dużo, ale jest to konsola która jest jeszcze młoda i się nie postarzała do tego stopnia, coś starszego może? Gier z NES’a, Pegasusa, Atari nie chciałem się chwytać, bo nie miałem styczności z nimi na tyle żeby móc się teraz o nich wypowiadać, no i te sprzęty ciężko zdobyć. No to może PlayStation 1? Wchodzę na YouTube i nie widzę polskich recenzji, mało kto zajmował się grami z szaraczka, a jak się ktoś znalazł to były to gry które każdy zna… W tym momencie pojawił się TEN pomysł. Stworzę kanał poświęcony grom na PSX… albo nie! Poświęcony wszystkim grom na PSX! I do tego ukazującym się po kolei! Tak przez miesiąc gromadziłem informacje o premierach gier na PSX i tworzyłem listę wszystkich gier wydawanych na świecie od 1994 do 1995 i zacząłem skupować po kolei każdą w rozsądnych cenach. W listopadzie dopiero zabrałem się za nagrywanie pierwszego materiału. Film nagrywałem PlayStation Vita, przy jednej lampie z parasolką. Pierwsza próba wydała mi się strasznie sztuczna, sztywna no i tragiczna. Podejście drugie, nagrałem, ale okazało się że nie włączyłem mikrofonu. No to do trzech razy sztuka, udało się. Nie jestem do końca dumny z tego pierwszego odcinka, bo nie byłem przyzwyczajony do gadania do kamery. Jakość tego filmu jest tragiczna i jestem tego świadom. Tekst również nie wypada za dobrze. Najważniejsze że nagrałem pierwszy odcinek i 23 listopada 2013 pojawił się on w sieci. Nie zrobił on dużej furory, bo aktywność była zerowa, ale czemu się dziwić.</p>
      <h2>Z czego jestem dumny?</h2>
      <p>Cieszyłem się jak dziecko z pierwszego „suba”, potem z 10, a jak miałem już 30 to mówiłem sobie że mam już pod sobą klasę która chce słuchać moich „wypocin”. Gdy było już 100 widzów, nie mogłem tego puścić cichaczem i stworzyłem TOP 30 moich gier dzieciństwa z PSX. Teraz, gdy jest Was aż 371! Jestem wniebowzięty i czekam aż pojawi się liczba czterocyfrowa! Jeżeli chodzi o odcinki, to najbardziej dumny jestem z tych, gdzie „coś” robię poza schematem. Chowam się do szafy z paczką zapałek, ukrywając się przed czymś i opowiadam o grze. Gdzie siedzę załamany ilością gier hazardowych i słyszę głosy. Gdzie pomaga mi „kamerzysta” który pomylił tryby REC z Pauzą i inne tego rodzaju. Jeżeli chodzi o najlepsze odcinki, to… to tak naprawdę trudno jest mi takie określić. Na pewno odcinek jubileuszowy, przy którym napracowałem się jak nigdy. Greenscreen, inny Jutuberzy (NRGeek, Bananowy Janek, Vaster, Cyber Marian, Arek Woźniak)  i tona pracy przy montażu i nagrywaniu.</p>
      <h2>Inne zainteresowania:</h2>
      <p>Z wiekiem jest ich coraz mniej niestety. Kiedyś deskorolka, rower – wyczynowo, rysunek, pisarstwo, fotografia. Dzisiaj pozostały mi: kinematografia, muzyka i książka.</p>
      <p>FILM: Pierwszy film który stworzyłem był zmontowany w średniej szkole, był to czterominutowy filmik pokazowy z Maxa Payne na modzie z Matrixa. Później poszedłem o krok dalej i zacząłem w szkole nagrywać z kolegami imprezy szkolne i filmiki promocyjne. Potem próbowałem nawet aktorstwa w filmie kolegi. Na wyższej uczelni miałem pierwszy raz styczność z pisaniem scenariusza (wraz z kolegą). Film, który stworzyliśmy zajął pierwsze miejsce w konkursie szkolnym, a był to komedio-dramat (z naciskiem na komedie) osadzony w czasach II wojny światowej. Jedynej rzeczy której się tam nie tykałem, była reżyserka którą zajmował się kolega. Grałem w tym filmie chyba z 3 role, odpowiadałem za dźwięk, nagrywanie, montaż, efekty specjalne, kończąc na transporcie. Jeszcze pojawiły się dwa projekty na Imagine Cup i nakręcenie dwóch wesel. Jeżeli chodzi o filmy kinowe i seriale, to jestem wielkim fanem kina akcji, lub sci-fi czy komiksowych ekranizacji (First Blood, Gwiezdne Wojny, Terminator, Predator, Avengers, Strażnicy Galaktyki, Iron Man). Na kolejnym miejscu są horrory! (Hellriser, Obcy, Koszmar z ulicy Wiązów, Mama, Klątwa). A tak to lubię dobrą komedię, zagadkowy thriller, czy biografię. Dobrą bajką lub filmem animowanym też nie pogardzę (Transformers: The Movie, Mulat, Toy Story, Up, Wall-E). No i trzeba by wspomnieć o serialach, które również oglądam, ale nie spodziewajcie się polskich tytułów, no chyba że 13 Posterunek (przynajmniej trzy pierwsze sezony). Aktualnie oglądam takie jak Supernatural, Game of Thrones, The Big Bang Theory, Utopia. Nie będę się rozpisywał na ich temat, polecam każdy, bo są one kompletnie inne i każdy znajdzie coś dla siebie.</p>
      <p>MUZYKA: Jeżeli chodzi o muzykę, to interesuję się nią od małego. Miałem styczność z każdego rodzaju muzyką, najbardziej do mnie przemawia rock i heavy metal. Zresztą to widać na moich filmach. Miałem również krótką przygodę z gitarą elektryczną, basową i perkusją. Na gitarze elektrycznej uczyłem się sam i w ogóle mi nie wychodziło, a jak mój kolega pożyczył ode mnie gitarę na dwa dni i jak oddawał i zagrał mi System of a Down, dałem sobie spokój. Jak sześć strun to dla mnie za dużo, to sobie wymyśliłem gitarę basową. Gra jest tak łatwa, że aż czasem nudna, odstawiłem. Najdłuższy i najbardziej produktywny okres to ten z perkusją. Perkusja to jedyny instrument na którym potrafię grać! Serio! Może nie gram jak pro, ale też nie kaleczę instrumentu aż tak bardzo.</p>
      <p>KSIĄŻKA: Co się tyczy książek, to przez szkołę miałem okropny wstręt do tego medium. W drugiej klasie liceum, kupiłem pierwszą w swoim życiu książkę i było to “Diablo Dziedzictwo Krwi”. Po tej lekturze pochłonąłem resztę książek o Diablo, Warcraft-a, Strażników Płomienia i na tym zaprzestałem na chwilę. Z braku innych książek, pożyczyłem od siostry Harrego Potter (tak wiem, śmiejcie się) którego przygoda wciągnęła mnie zaskakująco mocno, aż strawiłem całość. Ostatni tom to jedyna książka którą zacząłem czytać po szkole i skończyłem ją nad ranem. SZOK! Po tym znalazłem bardzo mroczne zakamarki książek i odnalazłem autora Briana Lumleya, którego wykreowany świat jest moim zdaniem lepszy od Lovecrafta. Oczywiście wyłączam Cthulhu, z którym nie chcę zadzierać, on jest najpotężniejszy i zawsze na propsach. Lumley i jego wizja wampirów jest tak oryginalna i brutalna, że z taką się jeszcze nigdzie nie spotkałem, polecam gorąco Nekroskop! Jak widzicie miałem styczność z fantasy, horrorem, a poza tym sci-fi i Gwiezdne Wojny (krótki epizodzik). Aktualnie kończę przedostatni tom Pieśni lodu i ognia, który zwany jest potocznie Grą o Tron (tak się zwie serial HBO i pierwszy tom książki).</p>
    </div>
  )
}

export default OMniePage